# Site settings
title: John's URL Shortener
author: John Goodliff
description: "A Jekyll & Javascript based URL shortener for personal use"
url: "l.johng.io"
github_link: "https://github.com/jerboa88/custom-url-shortener"

# Change the primary color of the entire site
theme_color: "#317b71"

# Build settings
markdown: kramdown
permalink: pretty

# Collection definitions and settings
collections:
  links:
    output: true
    permalink: /:path/


# Set default layout for link pages
defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
      type: links
    values:
      layout: link_page
